/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.dao.UserDao;
import org.example.models.User;

public class App {

    public static void main(String[] args) {
    }
}
